class AddALotOfColumns < ActiveRecord::Migration
  def self.up
    add_column :resources, :name10, :string
    add_column :resources, :name11, :string
    add_column :resources, :name12, :string
    add_column :resources, :name13, :string
    add_column :resources, :name14, :string
    add_column :resources, :name15, :string
    add_column :resources, :name16, :string
    add_column :resources, :name17, :string
    add_column :resources, :name18, :string
    add_column :resources, :name19, :string
    add_column :resources, :name20, :string
    add_column :resources, :name21, :string
    add_column :resources, :name22, :string
    add_column :resources, :name23, :string
    add_column :resources, :name24, :string
    add_column :resources, :name25, :string
    add_column :resources, :text_name10, :text
    add_column :resources, :text_name11, :text
    add_column :resources, :text_name12, :text
    add_column :resources, :text_name13, :text
    add_column :resources, :text_name14, :text
    add_column :resources, :text_name15, :text
    add_column :resources, :text_name16, :text
    add_column :resources, :text_name17, :text
    add_column :resources, :text_name18, :text
    add_column :resources, :text_name19, :text
    add_column :resources, :text_name20, :text
    add_column :resources, :text_name21, :text
    add_column :resources, :text_name22, :text
    add_column :resources, :text_name23, :text
    add_column :resources, :text_name24, :text
    add_column :resources, :text_name25, :text
    add_column :resources, :yet_another_name10, :string
    add_column :resources, :yet_another_name11, :string
    add_column :resources, :yet_another_name12, :string
    add_column :resources, :yet_another_name13, :string
    add_column :resources, :yet_another_name14, :string
    add_column :resources, :yet_another_name15, :string
    add_column :resources, :yet_another_name16, :string
    add_column :resources, :yet_another_name17, :string
    add_column :resources, :yet_another_name18, :string
    add_column :resources, :yet_another_name19, :string
    add_column :resources, :yet_another_name20, :string
    add_column :resources, :yet_another_name21, :string
    add_column :resources, :yet_another_name22, :string
    add_column :resources, :yet_another_name23, :string
    add_column :resources, :yet_another_name24, :string
    add_column :resources, :yet_another_name25, :string
    add_column :resources, :yet_another_text_name10, :text
    add_column :resources, :yet_another_text_name11, :text
    add_column :resources, :yet_another_text_name12, :text
    add_column :resources, :yet_another_text_name13, :text
    add_column :resources, :yet_another_text_name14, :text
    add_column :resources, :yet_another_text_name15, :text
    add_column :resources, :yet_another_text_name16, :text
    add_column :resources, :yet_another_text_name17, :text
    add_column :resources, :yet_another_text_name18, :text
    add_column :resources, :yet_another_text_name19, :text
    add_column :resources, :yet_another_text_name20, :text
    add_column :resources, :yet_another_text_name21, :text
    add_column :resources, :yet_another_text_name22, :text
    add_column :resources, :yet_another_text_name23, :text
    add_column :resources, :yet_another_text_name24, :text
    add_column :resources, :yet_another_text_name25, :text
    add_column :resources, :this_name10, :string
    add_column :resources, :this_name11, :string
    add_column :resources, :this_name12, :string
    add_column :resources, :this_name13, :string
    add_column :resources, :this_name14, :string
    add_column :resources, :this_name15, :string
    add_column :resources, :this_name16, :string
    add_column :resources, :this_name17, :string
    add_column :resources, :this_name18, :string
    add_column :resources, :this_name19, :string
    add_column :resources, :this_name20, :string
    add_column :resources, :this_name21, :string
    add_column :resources, :this_name22, :string
    add_column :resources, :this_name23, :string
    add_column :resources, :this_name24, :string
    add_column :resources, :this_name25, :string
    add_column :resources, :this_text_name10, :text
    add_column :resources, :this_text_name11, :text
    add_column :resources, :this_text_name12, :text
    add_column :resources, :this_text_name13, :text
    add_column :resources, :this_text_name14, :text
    add_column :resources, :this_text_name15, :text
    add_column :resources, :this_text_name16, :text
    add_column :resources, :this_text_name17, :text
    add_column :resources, :this_text_name18, :text
    add_column :resources, :this_text_name19, :text
    add_column :resources, :this_text_name20, :text
    add_column :resources, :this_text_name21, :text
    add_column :resources, :this_text_name22, :text
    add_column :resources, :this_text_name23, :text
    add_column :resources, :this_text_name24, :text
    add_column :resources, :this_text_name25, :text
    add_column :resources, :this_yet_another_name10, :string
    add_column :resources, :this_yet_another_name11, :string
    add_column :resources, :this_yet_another_name12, :string
    add_column :resources, :this_yet_another_name13, :string
    add_column :resources, :this_yet_another_name14, :string
    add_column :resources, :this_yet_another_name15, :string
    add_column :resources, :this_yet_another_name16, :string
    add_column :resources, :this_yet_another_name17, :string
    add_column :resources, :this_yet_another_name18, :string
    add_column :resources, :this_yet_another_name19, :string
    add_column :resources, :this_yet_another_name20, :string
    add_column :resources, :this_yet_another_name21, :string
    add_column :resources, :this_yet_another_name22, :string
    add_column :resources, :this_yet_another_name23, :string
    add_column :resources, :this_yet_another_name24, :string
    add_column :resources, :this_yet_another_name25, :string
    add_column :resources, :this_yet_another_text_name10, :text
    add_column :resources, :this_yet_another_text_name11, :text
    add_column :resources, :this_yet_another_text_name12, :text
    add_column :resources, :this_yet_another_text_name13, :text
    add_column :resources, :this_yet_another_text_name14, :text
    add_column :resources, :this_yet_another_text_name15, :text
    add_column :resources, :this_yet_another_text_name16, :text
    add_column :resources, :this_yet_another_text_name17, :text
    add_column :resources, :this_yet_another_text_name18, :text
    add_column :resources, :this_yet_another_text_name19, :text
    add_column :resources, :this_yet_another_text_name20, :text
    add_column :resources, :this_yet_another_text_name21, :text
    add_column :resources, :this_yet_another_text_name22, :text
    add_column :resources, :this_yet_another_text_name23, :text
    add_column :resources, :this_yet_another_text_name24, :text
    add_column :resources, :this_yet_another_text_name25, :text
  end

  def self.down
  end
end
